### ISSUE TITLE
:mailto and :tel

### ISSUE THREAD

**Issue by ianstormtaylor** [alanhogan/lessnmore#11]
Granted I didn't actually try mailto: so sorry if that's wrong. But tel: urls don't work as they get an http:// appended.

Would be really cool if they did (For now I just manually edited my database) because that is an awesome way to give out a telephone that bots wouldn't find.

(Also anything bad gonna happen from me editing that tel: in my database?)

**Comment by alanhogan** [comment]
@ianstormtaylor this should (finally) be fixed now in 2.3.0. LMK if you still have issues after upgrading to 2.3.0

**Comment by alanhogan** [comment]
i tried a `tel:` example and it actually works. pretty cool
