### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by miklb** [alanhogan/lessnmore#13]
Just upgraded from lessn to lessnmore, and trying to generate a new link I get this error

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.' in /home/www/litl.in/k/-/index.php:335 Stack trace: #0 /home/www/litl.in/k/-/index.php(335): PDO->prepare('SELECT custom_u...') #1

PHP version is 5.2.0.8 and MySQL version is mysql - 5.0.32

Any thoughts or suggestions? Hope this was the correct place to ask this.

**Comment by alanhogan** [comment]
Closing until I hear that this is still a problem for users on MySQL and PHP 5.6 or PHP 7.
