### ISSUE TITLE
web.config rule for IIS

### ISSUE THREAD

**Issue by bigworm** [alanhogan/lessnmore#24]
You should definitely double check me, but I got it to work on IIS by using the following rule in my web.config file

```
<rewrite>
    <rules>
        <rule name="rule 1m" stopProcessing="true">
	<match url="(.*)"  />
	<action type="Rewrite" url="/index.php?token={R:1}"  appendQueryString="true" />
		</rule>
    </rules>
</rewrite>
```

**Comment by alanhogan** [comment]
Thanks for this, @bigworm

**Comment by alanhogan** [comment]
I linked to this issue from the README — hopefully that's enough to help IIS users. Thanks again.
