### ISSUE TITLE
Does not work? (Can't log in)

### ISSUE THREAD

**Issue by Efreak** [alanhogan/lessnmore#29]
I'm trying to use sqlite primarily because I have no other reason to install mysql server (I'm running on an ODroid-C1, and have limited memory). Install.php runs fine, but then I can't log in.

I've checked to make sure my login credentials are the same as they are in the config file (I copy/pasted to make sure...).

When I hit enter or submit, I can see that the page loads again, but it loads the login page again, with the username and password still there.

I tried enabling logging in config.php, but it doesn't seem to do anything... There's no log file in the directory, and pages/php_errors.log doesn't exist. I have also tried moving the script out of the subdirectory I had it in (/shorturltest/-/ instead of /-/), and that doesn't work either.

**Comment by alanhogan** [comment]
It's rather hard to go on just this. Is there anything error you can point to? Maybe your host logs PHP errors somewhere you can find them, or something?

I will say that SQLite support is not very official in this project; it seems to work and I have accepted patches for it, but I did not develop for it. 

Still, there are many lessnmore users running on SQLite.

**Comment by Efreak** [comment]
I have no error logs. I tried enabling errors in the script, but it didn't have any effect in my server's error log or in the page's html output. If you have any suggestions for me, I can try them; I'm using php-fpm with nginx. I'll push the script to my server later and see if I can get any different results there.

**Comment by alanhogan** [comment]
@Efreak Does this fix your issue? https://github.com/alanhogan/lessnmore/pull/30

**Comment by Efreak** [comment]
I'm no longer using this, as I'm no longer using my odroid. I may start again, though. I suppose I'll close this since someone else seems to have fixed it.
