### ISSUE TITLE
TLS not supported

### ISSUE THREAD

**Issue by dosch** [alanhogan/lessnmore#31]
My website has a TLS certificate, but the links generated are HTTP. 
As I enforce TLS, the links do not work...

**Comment by alanhogan** [comment]
@dosch Okay, this seems like two issues to me.

1) As far as the generated links, I think it should be straightforward to add an option that should allow you to choose whether you want shortlinks to be prefixed with http or https.

2) Regarding the shortlinks “not working” — I am curious what that looks like. I assume that if you manually change the shortlink to use `https://`, it works. Can you confirm that?

My own website (alanhogan.com) is now 100% HTTPS-only, but I handle it by accepting HTTP requests and redirecting all of them to the same location but with the `https` protocol instead. (I'm not running LessnMore on that domain, of course). If your server were similarly configured, that might solve your problem.

**Comment by alanhogan** [comment]
See #32
